site_name: Machine Learning
site_author: Gavin Gao
site_url: https://ml.cgabc.xyz/
site_description: Machine Learning

repo_url: https://github.com/cggos/machine_learning
repo_name: cggos/machine_learning

theme: 
  name: material # readthedocs material
  # logo: material/library
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
  nav_style: light
  language: 'zh'
  # palette:
  #   primary: 'light blue'
  #   accent: 'indigo' 
  feature:
    tabs: true
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    # - toc.integrate
    - content.code.annotate

extra_javascript:
    - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

plugins:
  - search
  # - social
  - tags

markdown_extensions:
  - abbr
  - meta
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true # "#"
      toc_depth: 5
      separator: "_"
      slugify: !!python/name:pymdownx.slugs.uslugify_cased
  - codehilite:
      guess_lang: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde        
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences: [
        {name: mermaid, class: mermaid}
      ]
  - pymdownx.highlight:
      auto_title: true
      anchor_linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.tabbed:
      alternate_style: true       
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cggos
      name: cggos on GitHub
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/CGiABC
      name: CGABC on Twitter
        
nav:
  - Home: 'index.md'
  
  - 神经网络:
    - Overview: nn/README.md

  - 图神经网络:
    - Overview: gnn/README.md

  - Pytorch:
    - Overview: pytorch/README.md
